//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomLight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Essential
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public byte[] LogoImageData { get; set; }
        public string LogoImageMimeType { get; set; }
        public string About { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Boss { get; set; }
        public string Email { get; set; }
        public byte[] LogoImageInvertedData { get; set; }
        public string LogoImageInvertedMimeType { get; set; }
    }
}
