//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomLight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectImage
    {
        public int Id { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public int ProjectId { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
